[build]
  publish = "dist"
  command = "npm run build"

# Redirect rule for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle specific environment variables
[context.production.environment]
  NETLIFY = "true"

# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# MIME types
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript" 